### ISSUE TITLE
Catch2 merged into master - With it, type_safe compilation errors on all compilers

### ISSUE THREAD

**Issue by jamespharvey20** [foonathan/type_safe#61]
**EDIT: SOLVED.**  Changing `test/CMakeLists.txt` as shown below doesn't trigger {build}/test/catch.hpp to be replaced.  I wasn't paying attention that it's an `if(NOT EXISTS...`.  I thought I was trying non Catch2 versions, but Catch2 was remaining.

So, the fix is to become Catch2 compatible, or using the Catch1.x branch in the meantime if that's lengthy to do.

---

I'm extremely confused.  First time trying to use type_safe, and I can't get it to compile using gcc 7.2.0, clang 5.0.0, or Visual Studio 2017 15.5 Preview 2.  I'm just talking about git master, without any of my code or modifications.

**Catch v2 got merged into master today.**

I ran into another third party library today that doesn't work with Catch v2, so I tried if that was the issue by by changing `test/CMakeLists.txt` from

    https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp

to

    https://raw.githubusercontent.com/catchorg/Catch2/Catch1.x/single_include/catch.hpp
                                      ^^^^^^^^^^^^^^^^^^^^^^^^

But, I got the same errors.

I also tried Catch with tag v1.10.0 (Aug 26) to rule out recent Catch1.x changes as well, and got the same errors.

I also tried rolling type_safe back quite a few commits, and got the same errors.

Using Catch1.x on the other library worked, so I don't think there was any kind of crazy rebasing that screwed up the whole catch repo.

But, it looks like type_safe has been working for everyone, with the lack of issues saying otherwise, which leads me back to wondering if this is really a catch problem.  Any thoughts?

P.S. I did see #47, but that's different errors in a different file, and caused by him having an outdated version of `debug_assert.hpp`. I didn't have a previous version of it, so it's automatically grabbing [debug_assert master (5b1142e)](https://github.com/foonathan/debug_assert/commit/5b1142e84a2c585ed2648ba9b4f22ff7594479f9).

With clang 5.0.0:

```
[ 32%] Building CXX object test/CMakeFiles/type_safe_test.dir/strong_typedef.cpp.o
In file included from type_safe.git/test/strong_typedef.cpp:5:
type_safe.git/include/type_safe/strong_typedef.hpp:343:9: error: no matching function for call to
      'get_underlying'
        TYPE_SAFE_DETAIL_MAKE_OP(==, equality_comparison, bool)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
type_safe.git/include/type_safe/strong_typedef.hpp:234:22: note: expanded from macro
      'TYPE_SAFE_DETAIL_MAKE_OP'
            lhs)) Op detail::get_underlying<StrongTypedef>(detail::forward<Other>(rhs)));          \
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
type_safe.git/build.clang/test/catch.hpp:1040:80: note: in instantiation of function template
      specialization 'type_safe::strong_typedef_op::operator==<type, const convert_b &, void>' requested here
    auto compareEqual( LhsT const& lhs, RhsT const& rhs ) -> bool { return lhs == rhs; };
                                                                               ^
...
```

With gcc 7.2.0:

```
[ 32%] Building CXX object test/CMakeFiles/type_safe_test.dir/strong_typedef.cpp.o
In file included from type_safe.git/test/strong_typedef.cpp:5:0:
type_safe.git/include/type_safe/strong_typedef.hpp: In instantiation of ‘constexpr bool type_safe::strong_typedef_op::operator==(const type_safe::strong_typedef_op::equality_comparison<StrongTypedef>&, Other&&) [with StrongTypedef = ____C_A_T_C_H____T_E_S_T____0()::type; Other = const ____C_A_T_C_H____T_E_S_T____0()::convert_b&; <template-parameter-1-3> = void]’:
type_safe.git/build.gcc/test/catch.hpp:1040:80:   required from ‘bool Catch::compareEqual(const LhsT&, const RhsT&) [with LhsT = ____C_A_T_C_H____T_E_S_T____0()::type; RhsT = ____C_A_T_C_H____T_E_S_T____0()::convert_b]’
type_safe.git/build.gcc/test/catch.hpp:1069:63:   required from ‘const Catch::BinaryExpr<LhsT, const RhsT&> Catch::ExprLhs<LhsT>::operator==(const RhsT&) [with RhsT = ____C_A_T_C_H____T_E_S_T____0()::convert_b; LhsT = const ____C_A_T_C_H____T_E_S_T____0()::type&]’
type_safe.git/test/strong_typedef.cpp:55:9:   required from here
type_safe.git/include/type_safe/strong_typedef.hpp:234:59: error: no matching function for call to ‘get_underlying<____C_A_T_C_H____T_E_S_T____0()::type>(const ____C_A_T_C_H____T_E_S_T____0()::convert_b&)’
             lhs)) Op detail::get_underlying<StrongTypedef>(detail::forward<Other>(rhs)));          \
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
type_safe.git/include/type_safe/strong_typedef.hpp:343:9: note: in expansion of macro ‘TYPE_SAFE_DETAIL_MAKE_OP’
         TYPE_SAFE_DETAIL_MAKE_OP(==, equality_comparison, bool)
         ^~~~~~~~~~~~~~~~~~~~~~~~
...
```

With Visual Studio 2017 15.5 Preview 2:

```
type_safe.git\include\type_safe\strong_typedef.hpp(343): error C2665: 'type_safe::strong_typedef_op::detail::get_underlying': none of the 2 overloads could convert all the argument types
  type_safe.git\include\type_safe/strong_typedef.hpp(173): note: could be 'int &&type_safe::strong_typedef_op::detail::get_underlying<StrongTypedef>(StrongTypedef &&)'
          with
          [
              StrongTypedef=____C_A_T_C_H____T_E_S_T____0::type
          ]
  type_safe.git\include\type_safe/strong_typedef.hpp(166): note: or       'const int &type_safe::strong_typedef_op::detail::get_underlying<StrongTypedef>(const StrongTypedef &)'
          with
          [
              StrongTypedef=____C_A_T_C_H____T_E_S_T____0::type
          ]
  type_safe.git\include\type_safe/strong_typedef.hpp(343): note: while trying to match the argument list '(const ____C_A_T_C_H____T_E_S_T____0::convert_b)'
  build\x64-Debug\test\catch.hpp(1040): note: see reference to function template instantiation 'bool type_safe::strong_typedef_op::operator ==<____C_A_T_C_H____T_E_S_T____0::type,const RhsT&,void>(const type_safe::strong_typedef_op::equality_comparison<____C_A_T_C_H____T_E_S_T____0::type> &,Other)' being compiled
          with
          [
              RhsT=____C_A_T_C_H____T_E_S_T____0::convert_b,
              Other=const ____C_A_T_C_H____T_E_S_T____0::convert_b &
          ]
...
```

**Comment by foonathan** [comment]
Will take care of that next week.

**Comment by foonathan** [comment]
Done.
